// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/cloud.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HandleType    string                 `protobuf:"bytes,3,opt,name=handleType,proto3" json:"handleType,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_cloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListRequest) GetHandleType() string {
	if x != nil {
		return x.HandleType
	}
	return ""
}

func (x *ListRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_cloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HandleType    string                 `protobuf:"bytes,3,opt,name=handleType,proto3" json:"handleType,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_cloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetRequest) GetHandleType() string {
	if x != nil {
		return x.HandleType
	}
	return ""
}

func (x *GetRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_cloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HandleType    string                 `protobuf:"bytes,3,opt,name=handleType,proto3" json:"handleType,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_cloud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateRequest) GetHandleType() string {
	if x != nil {
		return x.HandleType
	}
	return ""
}

func (x *CreateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_cloud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HandleType    string                 `protobuf:"bytes,3,opt,name=handleType,proto3" json:"handleType,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_cloud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpdateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateRequest) GetHandleType() string {
	if x != nil {
		return x.HandleType
	}
	return ""
}

func (x *UpdateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_cloud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HandleType    string                 `protobuf:"bytes,3,opt,name=handleType,proto3" json:"handleType,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_cloud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *DeleteRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DeleteRequest) GetHandleType() string {
	if x != nil {
		return x.HandleType
	}
	return ""
}

func (x *DeleteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_cloud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_cloud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_cloud_proto_rawDescGZIP(), []int{10}
}

var File_proto_cloud_proto protoreflect.FileDescriptor

const file_proto_cloud_proto_rawDesc = "" +
	"\n" +
	"\x11proto/cloud.proto\x12\x05proto\"u\n" +
	"\vListRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"handleType\x18\x03 \x01(\tR\n" +
	"handleType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"&\n" +
	"\fListResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"t\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"handleType\x18\x03 \x01(\tR\n" +
	"handleType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"%\n" +
	"\vGetResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"w\n" +
	"\rCreateRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"handleType\x18\x03 \x01(\tR\n" +
	"handleType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"(\n" +
	"\x0eCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"w\n" +
	"\rUpdateRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"handleType\x18\x03 \x01(\tR\n" +
	"handleType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"(\n" +
	"\x0eUpdateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"w\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"handleType\x18\x03 \x01(\tR\n" +
	"handleType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"(\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"\a\n" +
	"\x05Empty2\x8e\x02\n" +
	"\rCloudProvider\x12/\n" +
	"\x04List\x12\x12.proto.ListRequest\x1a\x13.proto.ListResponse\x12,\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x123\n" +
	"\x04Post\x12\x14.proto.CreateRequest\x1a\x15.proto.CreateResponse\x122\n" +
	"\x03Put\x12\x14.proto.UpdateRequest\x1a\x15.proto.UpdateResponse\x125\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_cloud_proto_rawDescOnce sync.Once
	file_proto_cloud_proto_rawDescData []byte
)

func file_proto_cloud_proto_rawDescGZIP() []byte {
	file_proto_cloud_proto_rawDescOnce.Do(func() {
		file_proto_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cloud_proto_rawDesc), len(file_proto_cloud_proto_rawDesc)))
	})
	return file_proto_cloud_proto_rawDescData
}

var file_proto_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_cloud_proto_goTypes = []any{
	(*ListRequest)(nil),    // 0: proto.ListRequest
	(*ListResponse)(nil),   // 1: proto.ListResponse
	(*GetRequest)(nil),     // 2: proto.GetRequest
	(*GetResponse)(nil),    // 3: proto.GetResponse
	(*CreateRequest)(nil),  // 4: proto.CreateRequest
	(*CreateResponse)(nil), // 5: proto.CreateResponse
	(*UpdateRequest)(nil),  // 6: proto.UpdateRequest
	(*UpdateResponse)(nil), // 7: proto.UpdateResponse
	(*DeleteRequest)(nil),  // 8: proto.DeleteRequest
	(*DeleteResponse)(nil), // 9: proto.DeleteResponse
	(*Empty)(nil),          // 10: proto.Empty
}
var file_proto_cloud_proto_depIdxs = []int32{
	0, // 0: proto.CloudProvider.List:input_type -> proto.ListRequest
	2, // 1: proto.CloudProvider.Get:input_type -> proto.GetRequest
	4, // 2: proto.CloudProvider.Post:input_type -> proto.CreateRequest
	6, // 3: proto.CloudProvider.Put:input_type -> proto.UpdateRequest
	8, // 4: proto.CloudProvider.Delete:input_type -> proto.DeleteRequest
	1, // 5: proto.CloudProvider.List:output_type -> proto.ListResponse
	3, // 6: proto.CloudProvider.Get:output_type -> proto.GetResponse
	5, // 7: proto.CloudProvider.Post:output_type -> proto.CreateResponse
	7, // 8: proto.CloudProvider.Put:output_type -> proto.UpdateResponse
	9, // 9: proto.CloudProvider.Delete:output_type -> proto.DeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cloud_proto_init() }
func file_proto_cloud_proto_init() {
	if File_proto_cloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cloud_proto_rawDesc), len(file_proto_cloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cloud_proto_goTypes,
		DependencyIndexes: file_proto_cloud_proto_depIdxs,
		MessageInfos:      file_proto_cloud_proto_msgTypes,
	}.Build()
	File_proto_cloud_proto = out.File
	file_proto_cloud_proto_goTypes = nil
	file_proto_cloud_proto_depIdxs = nil
}
